### ISSUE TITLE
Bnar mới nhất không nhận tên

### ISSUE THREAD

**Issue by cjgawatama** [vinh-ttn/simcity#1]
![image](https://github.com/user-attachments/assets/b43083f7-fc4b-4520-8cfb-5577109a9e5f)

Mình cài bản mới nhất nhưng npc ko có tên theo bảng mà nhận tên kiểu npc thường thì fixx như thế nào bác

**Comment by vinh-ttn** [comment]
nv anh hùng ở sim Thành Thị đó giờ không có tên, chỉ có sim Chiến Loạn mới có

đã thêm tên ở sim Thành Thị hôm nay https://github.com/vinh-ttn/simcity/commit/66ceb78b65de046cd7aedef23a95da63d0abe3d6

thanks bác đã báo cáo
