### ISSUE TITLE
Fix Lỗi NPC Mất đầu, thiếu res

### ISSUE THREAD

**Issue by cjgawatama** [vinh-ttn/simcity#4]
Issue: https://www.facebook.com/groups/volamquan/posts/1415673265808528/

Nguyên nhân: một số src không có thư mục npcres_simple
Khắc phục:

-Tải file: [npcres_simple.zip](https://github.com/user-attachments/files/16530252/npcres_simple.zip)
-Giải nén
-Bỏ vào thư mục \\jxser\\server1\\settings\\
-Đồng bộ cả thư mục về Client đường dẫn tương tự
-Done
(Vẫn có một số rất ít bị thiếu res sẽ check lại res sau)

**Comment by vinh-ttn** [comment]
cám ơn bác, đã cập nhật hướng dẫn trong trang chính [commit](https://github.com/vinh-ttn/simcity/commit/ee1ce6ee42f80ae12159bb30416c9f5ccf6c6d0c)
